version: '3.4'
services:
  rasa:
    image: rasa/rasa:3.0.3-full
    ports:
     - 5015:5005
    volumes:
     - ./:/app
    container_name: rasa-bot
    command: run -m models --endpoints endpoints.yml

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: magical_password
      POSTGRES_USER: rasa_user

    volumes:
      - ./database_data:/var/lib/postgresql/data/