version: '3.4'
services:
  rasa:
    image: rasa/rasa:3.0.3-full
    ports:
     - 5015:5005
    volumes:
     - ./:/app
    container_name: rasa-bot
    command: >
      run
      --cors "*"
      --debug 
      --enable-api 
      -p 5015

  postgres:
    image: postgres:latest
    env_file:
      - database.env # configure postgres

    volumes:
      - ./database_data:/var/lib/postgresql/data/
      # copy the sql script to create tables
      - ./sql:/docker-entrypoint-initdb.d